### PR TITLE
Added derivative component, changed file structure, various other changes

### PR DESCRIPTION
**Pull request by matruane**

### CODE REVIEW

**Comment by JJJollyjim** [comment]
Very nice, are you able to resolve the conflicts and merge into master?

**Comment by matruane** [comment]
I'm unable to approve my own pull request.

**Comment by JJJollyjim** [comment]
I've got a 3-hour lab now, will fix conflicts and merge this evening.

**Comment by JJJollyjim** [comment]
Oh nevermind then ;-)

**Pull request merged**
